package tech-harmless:tcomp@0.0.1;

world testing {
    import hello: func() -> u32;
    export h-world: func() -> string;
    export data-process: func(data: list<u32>) -> option<list<u32>>;
}

world t2 {
    record abc {
        a: u32,
        b: u64,
        c: string,
    }
}
